export type UserRole = 'OWNER'|'ADMIN'|'MANAGER'|'ACCOUNTANT'|'OPERATOR'|'DRIVER'|'VIEWER';
export interface User { id:string; shopId:string; name:string; username:string; email?:string|null; phone?:string|null; role:UserRole; status:'ACTIVE'|'INACTIVE'|'LOCKED'; lastLoginAt?:string|null; createdAt?:string; updatedAt?:string }
export interface ApiResponse<T> { success:boolean; data:T; meta?: PaginationMeta }
export interface PaginationMeta { total:number; page:number; limit:number; pages:number; currentBalance?: string }
export interface Customer { id:string; shopId:string; customerCode:string; name:string; phone:string; alternatePhone?:string|null; businessName?:string|null; address?:string|null; area?:string|null; district?:string|null; notes?:string|null; creditLimit:string; currentBalance:string; avatarUrl?:string|null; status:'ACTIVE'|'INACTIVE'; createdAt:string; updatedAt:string; _count?:{purchases:number;payments:number;deliveries:number}; purchases?:Purchase[]; payments?:Payment[]; deliveries?:Delivery[] }
export interface Product { id:string; code:string; name:string; description?:string|null; unit:string; defaultPrice:string; isActive:boolean; categoryId?:string|null; category?:{id:string;name:string}|null; createdAt:string; updatedAt:string }
export interface PurchaseItem { id?:string; productId?:string|null; name:string; unit:string; quantity:string; unitPrice:string; discount:string; lineTotal?:string; note?:string|null }
export interface Invoice { id:string; invoiceNumber:string; status:'UNPAID'|'PARTIALLY_PAID'|'PAID'|'VOIDED'; subtotal:string; discount:string; previousDue:string; grandTotal:string; paidAmount:string; currentDue:string; invoiceDate:string; allocations?:unknown[] }
export interface Purchase { id:string; purchaseNumber:string; customerId:string; purchaseDate:string; status:'DRAFT'|'CONFIRMED'|'VOIDED'; subtotal:string; discount:string; netAmount:string; notes?:string|null; createdAt:string; customer:Customer; invoice?:Invoice|null; delivery?:Delivery|null; items?:PurchaseItem[] }
export interface PaymentAllocation { id?:string; invoiceId:string; amount:string; invoice?:Invoice }
export interface Payment { id:string; receiptNumber:string; customerId:string; paymentDate:string; amount:string; method:'CASH'|'BANK_TRANSFER'|'MOBILE_BANKING'|'CHEQUE'|'OTHER'; reference?:string|null; note?:string|null; status:'CONFIRMED'|'REVERSED'; reversalReason?:string|null; customer:Customer; allocations?:PaymentAllocation[]; createdAt:string }
export interface Driver { id:string; driverCode:string; name:string; phone:string; licenseNo?:string|null }
export interface Vehicle { id:string; registrationNumber:string; type:string; capacity?:string|null }
export type DeliveryStatus='PENDING'|'ASSIGNED'|'IN_TRANSIT'|'DELIVERED'|'CANCELLED';
export interface Delivery { id:string; deliveryNumber:string; customerId:string; status:DeliveryStatus; version:number; addressSnapshot:string; contactSnapshot:string; scheduledAt?:string|null; transportCharge:string; notes?:string|null; receiverName?:string|null; proofUrl?:string|null; createdAt:string; customer:Customer; driver?:Driver|null; vehicle?:Vehicle|null; purchase?:Purchase|null; invoice?:Invoice|null; history?:Array<{id:string;fromStatus?:DeliveryStatus|null;toStatus:DeliveryStatus;note?:string|null;createdAt:string}> }
export interface LedgerEntry { id:string; type:string; debit:string; credit:string; balanceAfter:string; sourceType:string; sourceId:string; description?:string|null; entryDate:string; createdAt:string }
export interface DashboardSummary { activeCustomers:number; totalDue:string; todaySales:string; monthSales:string; todayCollections:string; pendingDeliveries:number; recentPurchases:Purchase[]; recentPayments:Payment[] }
