import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { MapPin, Phone, Truck } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { Badge, ErrorBox, Loading, PageHeader } from '../components/ui';
import { apiError } from '../services/api';
import { deliveriesApi } from '../services/endpoints';
import type { DeliveryStatus } from '../types/api';
import { dateTimeBn, money } from '../utils/format';
const next:Record<DeliveryStatus,DeliveryStatus[]>={PENDING:['CANCELLED'],ASSIGNED:['IN_TRANSIT','CANCELLED'],IN_TRANSIT:['DELIVERED','CANCELLED'],DELIVERED:[],CANCELLED:[]};
export function DeliveryDetailsPage(){const {id=''}=useParams();const qc=useQueryClient();const q=useQuery({queryKey:['delivery',id],queryFn:()=>deliveriesApi.get(id),enabled:!!id});const m=useMutation({mutationFn:(status:DeliveryStatus)=>deliveriesApi.status(id,{status,version:q.data!.version}),onSuccess:()=>{qc.invalidateQueries({queryKey:['delivery',id]});qc.invalidateQueries({queryKey:['deliveries']})}});if(q.isLoading)return <Loading/>;if(q.error)return <ErrorBox message={apiError(q.error)}/>;const d=q.data!;return <><PageHeader title={`ডেলিভারি ${d.deliveryNumber}`} description={`${d.customer.name} · ${dateTimeBn(d.scheduledAt)}`} actions={<Badge tone={d.status==='DELIVERED'?'green':d.status==='CANCELLED'?'red':'blue'}>{d.status}</Badge>}/><div className="grid gap-5 lg:grid-cols-[1fr_340px]"><div className="space-y-5"><section className="lk-card p-5"><div className="grid gap-4 sm:grid-cols-2"><div className="flex gap-3"><MapPin className="text-blue-600"/><div><div className="text-xs text-slate-400">ঠিকানা</div><b>{d.addressSnapshot}</b></div></div><div className="flex gap-3"><Phone className="text-blue-600"/><div><div className="text-xs text-slate-400">যোগাযোগ</div><b>{d.contactSnapshot}</b></div></div><div className="flex gap-3"><Truck className="text-blue-600"/><div><div className="text-xs text-slate-400">ড্রাইভার</div><b>{d.driver?.name||'Assigned নয়'}</b></div></div><div><div className="text-xs text-slate-400">যানবাহন</div><b>{d.vehicle?.registrationNumber||'Assigned নয়'}</b></div><div><div className="text-xs text-slate-400">পরিবহন চার্জ</div><b>{money(d.transportCharge)}</b></div><div><div className="text-xs text-slate-400">Version</div><b>{d.version}</b></div></div></section><section className="lk-card p-5"><h3 className="font-bold text-slate-950">স্ট্যাটাস টাইমলাইন</h3><div className="mt-5 space-y-4">{d.history?.map(h=><div key={h.id} className="flex gap-3"><div className="mt-1 h-3 w-3 rounded-full bg-blue-600 ring-4 ring-blue-50"/><div><div className="font-bold text-slate-900">{h.toStatus}</div><div className="text-xs text-slate-400">{dateTimeBn(h.createdAt)}</div>{h.note&&<p className="mt-1 text-sm text-slate-500">{h.note}</p>}</div></div>)}</div></section></div><aside className="lk-card h-fit p-5"><h3 className="font-bold text-slate-950">স্ট্যাটাস আপডেট</h3>{d.status==='PENDING'&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">Backend status rule অনুযায়ী PENDING → ASSIGNED করতে driverId এবং vehicleId প্রয়োজন। কিন্তু backend-এ drivers/vehicles list endpoint নেই; তাই এই screen থেকে assignment করা নিরাপদ নয়।</p>}<div className="mt-4 grid gap-2">{next[d.status].map(s=><button key={s} disabled={m.isPending} onClick={()=>m.mutate(s)} className={`lk-btn ${s==='CANCELLED'?'bg-red-50 text-red-700':'bg-blue-600 text-white'}`}>{s}</button>)}</div>{m.error&&<div className="mt-3"><ErrorBox message={apiError(m.error)}/></div>}</aside></div></>}
