import { useQuery } from '@tanstack/react-query';
import { Plus, Truck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Badge, EmptyState, ErrorBox, Loading, PageHeader } from '../components/ui';
import { apiError } from '../services/api';
import { deliveriesApi } from '../services/endpoints';
import { dateTimeBn, money } from '../utils/format';
const tone=(s:string)=>s==='DELIVERED'?'green':s==='CANCELLED'?'red':s==='PENDING'?'amber':'blue';
export function DeliveriesPage(){const q=useQuery({queryKey:['deliveries'],queryFn:()=>deliveriesApi.list({page:1,limit:100})});if(q.isLoading)return <Loading/>;if(q.error)return <ErrorBox message={apiError(q.error)}/>;return <><PageHeader title="পরিবহন ও ডেলিভারি" description="Delivery assignment, status timeline এবং transport charge" actions={<Link to="/app/transport/deliveries/new" className="lk-btn-primary"><Plus size={17}/>নতুন ডেলিভারি</Link>}/><div className="mb-4 flex flex-wrap gap-2"><Link to="/app/transport/drivers" className="lk-btn-secondary">ড্রাইভার</Link><Link to="/app/transport/vehicles" className="lk-btn-secondary">যানবাহন</Link></div>{!q.data?.data.length?<div className="lk-card"><EmptyState title="কোনো ডেলিভারি নেই"/></div>:<div className="lk-table-wrap"><table className="lk-table"><thead><tr><th>ডেলিভারি</th><th>গ্রাহক</th><th>সময়সূচি</th><th>ড্রাইভার</th><th>যানবাহন</th><th>চার্জ</th><th>স্ট্যাটাস</th><th></th></tr></thead><tbody>{q.data.data.map(d=><tr key={d.id}><td><div className="flex items-center gap-2"><Truck size={17} className="text-blue-600"/><b className="font-mono text-xs">{d.deliveryNumber}</b></div></td><td><b>{d.customer.name}</b><div className="text-xs text-slate-400">{d.contactSnapshot}</div></td><td>{dateTimeBn(d.scheduledAt)}</td><td>{d.driver?.name||'—'}</td><td>{d.vehicle?.registrationNumber||'—'}</td><td>{money(d.transportCharge)}</td><td><Badge tone={tone(d.status) as any}>{d.status}</Badge></td><td><Link to={`/app/transport/deliveries/${d.id}`} className="font-bold text-blue-600">দেখুন</Link></td></tr>)}</tbody></table></div>}</>}
