import { zodResolver } from '@hookform/resolvers/zod';
import { Eye, EyeOff, LockKeyhole, ShieldCheck, Truck, UserRound } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { useLocation, useNavigate } from 'react-router-dom';
import { z } from 'zod';
import { Brand } from '../components/Brand';
import { apiError } from '../services/api';
import { authApi } from '../services/endpoints';
import { useAuthStore } from '../stores/auth';

const schema=z.object({identifier:z.string().trim().min(3,'ইউজারনেম/ইমেইল/ফোন দিন'),password:z.string().min(8,'পাসওয়ার্ড কমপক্ষে ৮ অক্ষরের হতে হবে')});
type Form=z.infer<typeof schema>;
export function LoginPage(){const [show,setShow]=useState(false);const [serverError,setServerError]=useState('');const nav=useNavigate();const loc=useLocation();const auth=useAuthStore();const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Form>({resolver:zodResolver(schema)});
const submit=async(v:Form)=>{setServerError('');try{const data=await authApi.login(v);const me=await authApi.me();auth.setSession(me.user,me.permissions);const from=(loc.state as any)?.from||'/app/dashboard';nav(from,{replace:true})}catch(e){setServerError(apiError(e))}};
return <main className="min-h-screen lg:grid lg:grid-cols-[1.08fr_.92fr]">
<section className="relative hidden overflow-hidden bg-gradient-to-br from-slate-950 via-slate-900 to-blue-700 p-12 text-white lg:flex lg:flex-col lg:justify-between xl:p-16"><div className="absolute -right-40 -top-40 h-[450px] w-[450px] rounded-full bg-white/10"/><div className="relative"><Brand inverse/></div><div className="relative max-w-2xl"><h1 className="text-5xl font-bold leading-[1.15] tracking-tight xl:text-6xl">আপনার ব্যবসার হিসাব ও লজিস্টিকস—এক জায়গায়।</h1><p className="mt-5 max-w-xl text-lg leading-8 text-white/70">ক্রয়, ইনভয়েস, বকেয়া, পেমেন্ট, পরিবহন এবং গ্রাহক ব্যবস্থাপনা আরও সহজ, দ্রুত ও নির্ভরযোগ্যভাবে পরিচালনা করুন।</p><div className="mt-8 flex flex-wrap gap-3 text-sm text-white/80"><span className="rounded-full border border-white/15 bg-white/10 px-4 py-2">রিয়েল-টাইম হিসাব</span><span className="rounded-full border border-white/15 bg-white/10 px-4 py-2">সুরক্ষিত RBAC</span><span className="rounded-full border border-white/15 bg-white/10 px-4 py-2">Web + Mobile API</span></div></div><div className="relative text-xs text-white/45">© 2026 LogiKhata. Smart Logistics, Sales, Collection and Due Management.</div></section>
<section className="grid min-h-screen place-items-center p-5 md:p-10"><div className="w-full max-w-[510px]"><div className="mb-6 lg:hidden"><Brand/></div><div className="rounded-[20px] border border-slate-200/80 bg-white/95 p-6 shadow-[0_24px_70px_rgba(15,23,42,.10)] backdrop-blur md:p-10"><div className="mb-7"><h2 className="text-3xl font-bold tracking-tight text-slate-950">স্বাগতম</h2><p className="mt-2 text-sm leading-6 text-slate-500">আপনার LogiKhata অ্যাকাউন্টে সাইন ইন করুন।</p></div>{serverError&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{serverError}</div>}<form onSubmit={handleSubmit(submit)} className="space-y-4"><label className="block"><span className="lk-label">ইউজারনেম / ইমেইল / ফোন</span><div className="relative"><UserRound className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={20}/><input {...register('identifier')} className="lk-input min-h-[54px] pl-12" placeholder="owner বা owner@example.com"/></div>{errors.identifier&&<small className="mt-1 block text-red-600">{errors.identifier.message}</small>}</label><label className="block"><span className="lk-label">পাসওয়ার্ড</span><div className="relative"><LockKeyhole className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={20}/><input {...register('password')} type={show?'text':'password'} className="lk-input min-h-[54px] pl-12 pr-12" placeholder="পাসওয়ার্ড লিখুন"/><button type="button" onClick={()=>setShow(s=>!s)} className="absolute right-2 top-1/2 grid h-10 w-10 -translate-y-1/2 place-items-center rounded-xl text-slate-400 hover:bg-blue-50 hover:text-blue-600">{show?<EyeOff size={20}/>:<Eye size={20}/>}</button></div>{errors.password&&<small className="mt-1 block text-red-600">{errors.password.message}</small>}</label><button disabled={isSubmitting} className="lk-btn-primary min-h-[54px] w-full">{isSubmitting?'সাইন ইন হচ্ছে...':'সাইন ইন করুন'}</button></form><div className="mt-5 flex items-center justify-center gap-2 text-xs text-slate-400"><ShieldCheck size={16} className="text-green-600"/>সুরক্ষিত JWT সেশন এবং HttpOnly refresh cookie</div></div><div className="mt-5 flex items-center justify-center gap-2 text-xs text-slate-400"><Truck size={15}/>LogiKhata Enterprise ERP</div></div></section>
</main>}
