import { useMutation, useQuery } from '@tanstack/react-query';
import { Save } from 'lucide-react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ErrorBox, Field, Loading, PageHeader } from '../components/ui';
import { apiError } from '../services/api';
import { customersApi, deliveriesApi } from '../services/endpoints';
import { normalizeMoney } from '../utils/format';
export function NewDeliveryPage(){const nav=useNavigate();const c=useQuery({queryKey:['customers','delivery-select'],queryFn:()=>customersApi.list({page:1,limit:100,status:'ACTIVE'})});const [form,setForm]=useState({customerId:'',address:'',contact:'',scheduledAt:'',transportCharge:'0',notes:''});const m=useMutation({mutationFn:()=>deliveriesApi.create({customerId:form.customerId,address:form.address,contact:form.contact,scheduledAt:form.scheduledAt?new Date(form.scheduledAt).toISOString():undefined,transportCharge:normalizeMoney(form.transportCharge),notes:form.notes||undefined}),onSuccess:(d)=>nav(`/app/transport/deliveries/${d.id}`)});if(c.isLoading)return <Loading/>;return <><PageHeader title="নতুন ডেলিভারি" description="Unassigned delivery PENDING হিসেবে তৈরি হবে"/><section className="lk-card overflow-hidden"><div className="grid gap-5 p-5 md:grid-cols-2"><div className="md:col-span-2"><Field label="গ্রাহক" required><select className="lk-input" value={form.customerId} onChange={e=>{const id=e.target.value;const x=c.data?.data.find(y=>y.id===id);setForm({...form,customerId:id,address:x?.address||form.address,contact:x?.phone||form.contact})}}><option value="">গ্রাহক নির্বাচন</option>{c.data?.data.map(x=><option key={x.id} value={x.id}>{x.customerCode} — {x.name}</option>)}</select></Field></div><Field label="ডেলিভারি ঠিকানা" required><input className="lk-input" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></Field><Field label="যোগাযোগ" required><input className="lk-input" value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/></Field><Field label="সময়সূচি"><input type="datetime-local" className="lk-input" value={form.scheduledAt} onChange={e=>setForm({...form,scheduledAt:e.target.value})}/></Field><Field label="পরিবহন চার্জ"><input type="number" min="0" step="0.01" className="lk-input" value={form.transportCharge} onChange={e=>setForm({...form,transportCharge:e.target.value})}/></Field><div className="md:col-span-2"><Field label="নোট"><textarea className="lk-input min-h-28" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div>{m.error&&<div className="md:col-span-2"><ErrorBox message={apiError(m.error)}/></div>}</div><div className="flex justify-end border-t border-slate-200 bg-slate-50 p-5"><button disabled={!form.customerId||!form.address||!form.contact||m.isPending} onClick={()=>m.mutate()} className="lk-btn-primary"><Save size={17}/>ডেলিভারি তৈরি করুন</button></div></section></>}
