import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Printer, RotateCcw } from 'lucide-react';
import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { Badge, ErrorBox, Loading, PageHeader } from '../components/ui';
import { apiError } from '../services/api';
import { paymentsApi } from '../services/endpoints';
import { dateBn, money } from '../utils/format';
export function PaymentDetailsPage(){const {id=''}=useParams();const qc=useQueryClient();const [reason,setReason]=useState('');const q=useQuery({queryKey:['payment',id],queryFn:()=>paymentsApi.get(id),enabled:!!id});const rev=useMutation({mutationFn:()=>paymentsApi.reverse(id,reason),onSuccess:()=>{qc.invalidateQueries({queryKey:['payment',id]});qc.invalidateQueries({queryKey:['payments']});qc.invalidateQueries({queryKey:['dashboard']});setReason('')}});if(q.isLoading)return <Loading/>;if(q.error)return <ErrorBox message={apiError(q.error)}/>;const p=q.data!;return <><PageHeader title={`রিসিট ${p.receiptNumber}`} description={`${dateBn(p.paymentDate)} · ${p.customer.name}`} actions={<button onClick={()=>window.print()} className="lk-btn-secondary"><Printer size={17}/>প্রিন্ট</button>}/><div className="grid gap-5 lg:grid-cols-[1fr_340px]"><section className="lk-card p-6"><div className="flex items-center justify-between border-b border-slate-200 pb-5"><div><div className="text-xs text-slate-400">প্রাপ্ত পরিমাণ</div><div className="mt-1 text-3xl font-bold text-green-700">{money(p.amount)}</div></div><Badge tone={p.status==='CONFIRMED'?'green':'red'}>{p.status}</Badge></div><div className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><span className="text-slate-400">গ্রাহক</span><div className="font-bold">{p.customer.name}</div></div><div><span className="text-slate-400">মেথড</span><div className="font-bold">{p.method}</div></div><div><span className="text-slate-400">রেফারেন্স</span><div className="font-bold">{p.reference||'—'}</div></div><div><span className="text-slate-400">নোট</span><div className="font-bold">{p.note||'—'}</div></div></div><h3 className="mt-7 font-bold text-slate-950">Invoice Allocation</h3><div className="mt-3 overflow-x-auto rounded-xl border border-slate-200"><table className="lk-table"><thead><tr><th>ইনভয়েস</th><th>Allocated</th><th>Invoice Due</th></tr></thead><tbody>{p.allocations?.map((a,i)=><tr key={a.id||i}><td>{a.invoice?.invoiceNumber||a.invoiceId}</td><td>{money(a.amount)}</td><td>{money(a.invoice?.currentDue||0)}</td></tr>)}</tbody></table></div></section><aside className="lk-card h-fit p-5"><h3 className="font-bold text-slate-950">Reversal</h3><p className="mt-2 text-xs leading-5 text-slate-500">Financial record delete না করে backend compensating reversal তৈরি করে।</p>{p.status==='CONFIRMED'?<><textarea className="lk-input mt-4 min-h-24" placeholder="Reversal reason (কমপক্ষে ৫ অক্ষর)" value={reason} onChange={e=>setReason(e.target.value)}/><button disabled={reason.trim().length<5||rev.isPending} onClick={()=>rev.mutate()} className="lk-btn mt-3 w-full bg-red-600 text-white"><RotateCcw size={17}/>পেমেন্ট রিভার্স করুন</button>{rev.error&&<div className="mt-3"><ErrorBox message={apiError(rev.error)}/></div>}</>:<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">এই পেমেন্ট রিভার্স করা হয়েছে। {p.reversalReason&&`কারণ: ${p.reversalReason}`}</div>}</aside></div></>}
