import type { ReactNode } from 'react';
import { AlertTriangle, LoaderCircle, Search, X } from 'lucide-react';
import { clsx } from 'clsx';

export function PageHeader({title,description,actions}:{title:string;description?:string;actions?:ReactNode}){return <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="lk-page-title">{title}</h1>{description&&<p className="mt-1 text-sm text-slate-500">{description}</p>}</div>{actions}</div>}
export function Loading({label='লোড হচ্ছে...'}:{label?:string}){return <div className="grid min-h-52 place-items-center"><div className="flex items-center gap-2 text-sm font-semibold text-slate-500"><LoaderCircle className="animate-spin" size={20}/>{label}</div></div>}
export function ErrorBox({message}:{message:string}){return <div className="lk-card flex items-start gap-3 border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertTriangle size={19}/><div><b>সমস্যা হয়েছে</b><p className="mt-1">{message}</p></div></div>}
export function EmptyState({title='কোনো ডাটা পাওয়া যায়নি',description}:{title?:string;description?:string}){return <div className="grid min-h-48 place-items-center p-6 text-center"><div><div className="mx-auto mb-3 grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-slate-400"><Search/></div><div className="font-bold text-slate-800">{title}</div>{description&&<p className="mt-1 text-sm text-slate-500">{description}</p>}</div></div>}
export function SearchInput({value,onChange,placeholder='খুঁজুন...'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="relative min-w-0 flex-1 sm:min-w-[260px]"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input className="lk-input pl-10 pr-10" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button type="button" onClick={()=>onChange('')} className="absolute right-2 top-1/2 grid h-8 w-8 -translate-y-1/2 place-items-center rounded-lg text-slate-400 hover:bg-slate-100"><X size={16}/></button>}</div>}
export function Badge({children,tone='slate'}:{children:ReactNode;tone?:'slate'|'blue'|'green'|'amber'|'red'}){const c={slate:'bg-slate-100 text-slate-600',blue:'bg-blue-50 text-blue-700',green:'bg-green-50 text-green-700',amber:'bg-amber-50 text-amber-700',red:'bg-red-50 text-red-700'}[tone];return <span className={clsx('lk-badge',c)}>{children}</span>}
export function StatCard({label,value,icon,tone='blue',foot}:{label:string;value:ReactNode;icon:ReactNode;tone?:'blue'|'green'|'red'|'amber'|'sky';foot?:string}){const c={blue:'bg-blue-50 text-blue-600',green:'bg-green-50 text-green-600',red:'bg-red-50 text-red-600',amber:'bg-amber-50 text-amber-600',sky:'bg-sky-50 text-sky-600'}[tone];return <div className="lk-card relative overflow-hidden p-5"><div className={clsx('mb-4 grid h-11 w-11 place-items-center rounded-2xl',c)}>{icon}</div><p className="text-xs font-medium text-slate-500">{label}</p><div className="mt-1 text-2xl font-bold tracking-tight text-slate-950">{value}</div>{foot&&<div className="mt-2 text-xs text-slate-400">{foot}</div>}</div>}
export function Field({label,children,required=false,help}:{label:string;children:ReactNode;required?:boolean;help?:string}){return <label className="block"><span className="lk-label">{label}{required&&<span className="text-red-500"> *</span>}</span>{children}{help&&<span className="mt-1 block text-xs text-slate-400">{help}</span>}</label>}
export function BackendGap({title,children}:{title:string;children:ReactNode}){return <div className="lk-card border-amber-200 bg-amber-50 p-5"><div className="mb-1 flex items-center gap-2 font-bold text-amber-900"><AlertTriangle size={18}/>{title}</div><div className="text-sm leading-6 text-amber-800">{children}</div></div>}
